In [2]:
from keras.layers import Embedding,LSTM,Dense,SimpleRNN
from keras import models
from keras import layers
import numpy as np
import json

Using TensorFlow backend.
G:\anaconda\envs\Aimusic\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
G:\anaconda\envs\Aimusic\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
G:\anaconda\envs\Aimusic\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
G:\anaconda\envs\Aimusic\lib\site-packages\tensorflow\python\framework\dtypes.py

In [4]:
model = models.Sequential()
model.add(layers.GRU(20))
model.add(layers.Dense(27,activation='softmax'))

In [6]:
model_2 = models.Sequential()
model_2.add(layers.GRU(20))
model_2.add(layers.Dense(10,activation='softmax'))

In [7]:
model.compile(optimizer='rmsprop',
             loss='categorical_crossentropy',
             metrics=['accuracy'])
model_2.compile(optimizer='rmsprop',
             loss='categorical_crossentropy',
             metrics=['accuracy'])

In [8]:
obj_train=open("./test/json/sunny_train.json")
input_train=json.load(obj_train)
input_train=np.array(input_train)

In [9]:

obj_output1=open("./test/json/sunny_output1.json")
output_train_1=json.load(obj_output1)
output_train_1=np.array(output_train_1)

note_train = np.zeros((len(output_train_1),27))
for i in range(len(output_train_1)):
    index = int(output_train_1[i]*2)
    note_train[i][index] = 1

time_train = np.zeros((len(output_train_1),10))
obj_output2=open("./test/json/sunny_output2.json")
output_train_2=json.load(obj_output2)
output_train_2=np.array(output_train_2)
for i in range(len(output_train_2)):
    index = int(output_train_2[i]/0.25 -1)
    time_train[i][index] = 1
    

print(time_train)
print(note_train)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
history=model.fit(input_train,note_train,batch_size=1,epochs=500)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/500
290/290 [==============================] - 5s 18ms/step - loss: 2.7555 - acc: 0.1483
Epoch 2/500
290/290 [==============================] - 4s 12ms/step - loss: 2.4515 - acc: 0.1862
Epoch 3/500
290/290 [==============================] - 3s 12ms/step - loss: 2.4202 - acc: 0.1966
Epoch 4/500
290/290 [==============================] - 3s 12ms/step - loss: 2.3869 - acc: 0.2414
Epoch 5/500
290/290 [==============================] - 4s 13ms/step - loss: 2.3956 - acc: 0.2276
Epoch 6/500
290/290 [==============================] - 4s 14ms/step - loss: 2.3383 - acc: 0.2517
Epoch 7/500
290/290 [==============================] - 4s 14ms/step - loss: 2.3227 - acc: 0.2414
Epoch 8/500
290/290 [==============================] - 3s 11ms/step - loss: 2.2762 - acc: 0.2690
Epoch 9/500
290/290 [==============================] - 5s 16ms/step - loss: 2.2690 - acc: 0.2655
Epoch 10/500
290/290 [===========

290/290 [==============================] - 4s 13ms/step - loss: 1.7183 - acc: 0.4207
Epoch 82/500
290/290 [==============================] - 4s 12ms/step - loss: 1.7154 - acc: 0.4172
Epoch 83/500
290/290 [==============================] - 4s 12ms/step - loss: 1.7412 - acc: 0.3931
Epoch 84/500
290/290 [==============================] - 3s 11ms/step - loss: 1.7032 - acc: 0.4138
Epoch 85/500
290/290 [==============================] - 3s 10ms/step - loss: 1.6999 - acc: 0.4207
Epoch 86/500
290/290 [==============================] - 3s 10ms/step - loss: 1.7152 - acc: 0.4207
Epoch 87/500
290/290 [==============================] - 3s 10ms/step - loss: 1.6920 - acc: 0.4379
Epoch 88/500
290/290 [==============================] - 3s 10ms/step - loss: 1.6985 - acc: 0.4103
Epoch 89/500
290/290 [==============================] - 3s 10ms/step - loss: 1.6989 - acc: 0.4310
Epoch 90/500
290/290 [==============================] - 4s 14ms/step - loss: 1.6789 - acc: 0.4379
Epoch 91/500
290/290 [===========

290/290 [==============================] - 3s 11ms/step - loss: 1.3386 - acc: 0.5793
Epoch 164/500
290/290 [==============================] - 3s 11ms/step - loss: 1.3219 - acc: 0.6103
Epoch 165/500
290/290 [==============================] - 3s 10ms/step - loss: 1.3808 - acc: 0.5690
Epoch 166/500
290/290 [==============================] - 3s 10ms/step - loss: 1.3383 - acc: 0.5966
Epoch 167/500
290/290 [==============================] - 3s 10ms/step - loss: 1.3140 - acc: 0.6069
Epoch 168/500
290/290 [==============================] - 3s 10ms/step - loss: 1.3280 - acc: 0.6000
Epoch 169/500
290/290 [==============================] - 3s 12ms/step - loss: 1.3161 - acc: 0.6138
Epoch 170/500
290/290 [==============================] - 4s 15ms/step - loss: 1.3223 - acc: 0.6069
Epoch 171/500
290/290 [==============================] - 4s 13ms/step - loss: 1.3235 - acc: 0.6310
Epoch 172/500
290/290 [==============================] - 3s 11ms/step - loss: 1.3106 - acc: 0.5966
Epoch 173/500
290/290 [=

290/290 [==============================] - 3s 10ms/step - loss: 1.0017 - acc: 0.7069
Epoch 246/500
290/290 [==============================] - 3s 10ms/step - loss: 0.9524 - acc: 0.7103
Epoch 247/500
290/290 [==============================] - 3s 10ms/step - loss: 0.9321 - acc: 0.7207
Epoch 248/500
290/290 [==============================] - 3s 10ms/step - loss: 0.9661 - acc: 0.7069
Epoch 249/500
290/290 [==============================] - 3s 10ms/step - loss: 0.9139 - acc: 0.7517
Epoch 250/500
290/290 [==============================] - 3s 10ms/step - loss: 0.8946 - acc: 0.7448
Epoch 251/500
290/290 [==============================] - 3s 10ms/step - loss: 0.8977 - acc: 0.7586
Epoch 252/500
290/290 [==============================] - 3s 10ms/step - loss: 0.9468 - acc: 0.7448
Epoch 253/500
290/290 [==============================] - 3s 10ms/step - loss: 0.9021 - acc: 0.7345
Epoch 254/500
290/290 [==============================] - 3s 10ms/step - loss: 0.9652 - acc: 0.7310
Epoch 255/500
290/290 [=

290/290 [==============================] - 4s 14ms/step - loss: 0.7655 - acc: 0.7655
Epoch 328/500
290/290 [==============================] - 3s 10ms/step - loss: 0.7179 - acc: 0.7862
Epoch 329/500
290/290 [==============================] - 3s 10ms/step - loss: 0.7047 - acc: 0.7862
Epoch 330/500
290/290 [==============================] - 3s 10ms/step - loss: 0.7357 - acc: 0.7828
Epoch 331/500
290/290 [==============================] - 3s 10ms/step - loss: 0.7041 - acc: 0.8069
Epoch 332/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6977 - acc: 0.7897
Epoch 333/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6850 - acc: 0.8000
Epoch 334/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6924 - acc: 0.8069
Epoch 335/500
290/290 [==============================] - 3s 10ms/step - loss: 0.7063 - acc: 0.7897
Epoch 336/500
290/290 [==============================] - 3s 10ms/step - loss: 0.7409 - acc: 0.7724
Epoch 337/500
290/290 [=

290/290 [==============================] - 5s 18ms/step - loss: 0.5872 - acc: 0.8759
Epoch 410/500
290/290 [==============================] - 5s 17ms/step - loss: 0.6012 - acc: 0.8483
Epoch 411/500
290/290 [==============================] - 5s 16ms/step - loss: 0.5572 - acc: 0.8379: 3s - 
Epoch 412/500
290/290 [==============================] - 3s 11ms/step - loss: 0.5541 - acc: 0.8414
Epoch 413/500
290/290 [==============================] - 5s 16ms/step - loss: 0.5570 - acc: 0.8621: 0s - loss: 0.5319 -
Epoch 414/500
290/290 [==============================] - 4s 15ms/step - loss: 0.5191 - acc: 0.8552
Epoch 415/500
290/290 [==============================] - 4s 13ms/step - loss: 0.5698 - acc: 0.8586
Epoch 416/500
290/290 [==============================] - 4s 13ms/step - loss: 0.6883 - acc: 0.8310
Epoch 417/500
290/290 [==============================] - 5s 16ms/step - loss: 0.5851 - acc: 0.8586
Epoch 418/500
290/290 [==============================] - 5s 19ms/step - loss: 0.5623 - acc: 0.8

290/290 [==============================] - 8s 28ms/step - loss: 0.4338 - acc: 0.8966
Epoch 492/500
290/290 [==============================] - 7s 24ms/step - loss: 0.4456 - acc: 0.8966
Epoch 493/500
290/290 [==============================] - 5s 16ms/step - loss: 0.4694 - acc: 0.8828
Epoch 494/500
290/290 [==============================] - 7s 24ms/step - loss: 0.5301 - acc: 0.8621
Epoch 495/500
290/290 [==============================] - 6s 22ms/step - loss: 0.4689 - acc: 0.8793
Epoch 496/500
290/290 [==============================] - 10s 34ms/step - loss: 0.5966 - acc: 0.8552 0s - loss: 0.5992
Epoch 497/500
290/290 [==============================] - 7s 23ms/step - loss: 0.5188 - acc: 0.8621
Epoch 498/500
290/290 [==============================] - 5s 16ms/step - loss: 0.4794 - acc: 0.8862
Epoch 499/500
290/290 [==============================] - 4s 14ms/step - loss: 0.4783 - acc: 0.8931
Epoch 500/500
290/290 [==============================] - 5s 17ms/step - loss: 0.4690 - acc: 0.8759


In [12]:
history=model_2.fit(input_train,time_train,batch_size=1,epochs=500)

Epoch 1/500
290/290 [==============================] - 6s 21ms/step - loss: 1.1443 - acc: 0.6690
Epoch 2/500
290/290 [==============================] - 6s 20ms/step - loss: 0.8967 - acc: 0.7310
Epoch 3/500
290/290 [==============================] - 7s 23ms/step - loss: 0.8975 - acc: 0.7310
Epoch 4/500
290/290 [==============================] - 5s 18ms/step - loss: 0.8877 - acc: 0.7310: 0s - loss: 0.8879 - ac
Epoch 5/500
290/290 [==============================] - 7s 25ms/step - loss: 0.8792 - acc: 0.7310
Epoch 6/500
290/290 [==============================] - 8s 27ms/step - loss: 0.8727 - acc: 0.7310
Epoch 7/500
290/290 [==============================] - 7s 23ms/step - loss: 0.8662 - acc: 0.7310
Epoch 8/500
290/290 [==============================] - 6s 22ms/step - loss: 0.8577 - acc: 0.7310
Epoch 9/500
290/290 [==============================] - 9s 30ms/step - loss: 0.8561 - acc: 0.7310
Epoch 10/500
290/290 [==============================] - 5s 19ms/step - loss: 0.8460 - acc: 0.7310
Epoch

290/290 [==============================] - 3s 10ms/step - loss: 0.6870 - acc: 0.7655
Epoch 84/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6675 - acc: 0.7793
Epoch 85/500
290/290 [==============================] - 3s 11ms/step - loss: 0.6706 - acc: 0.7724
Epoch 86/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6593 - acc: 0.7655
Epoch 87/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6858 - acc: 0.7655
Epoch 88/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6878 - acc: 0.7690
Epoch 89/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6824 - acc: 0.7793
Epoch 90/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6531 - acc: 0.7931
Epoch 91/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6521 - acc: 0.7586
Epoch 92/500
290/290 [==============================] - 3s 10ms/step - loss: 0.6502 - acc: 0.7724
Epoch 93/500
290/290 [===========

290/290 [==============================] - 4s 13ms/step - loss: 0.3930 - acc: 0.8759
Epoch 166/500
290/290 [==============================] - 3s 10ms/step - loss: 0.4015 - acc: 0.8828
Epoch 167/500
290/290 [==============================] - 3s 10ms/step - loss: 0.3790 - acc: 0.8724
Epoch 168/500
290/290 [==============================] - 3s 11ms/step - loss: 0.3817 - acc: 0.8862
Epoch 169/500
290/290 [==============================] - 3s 11ms/step - loss: 0.3954 - acc: 0.8828
Epoch 170/500
290/290 [==============================] - 3s 10ms/step - loss: 0.3750 - acc: 0.8759
Epoch 171/500
290/290 [==============================] - 3s 10ms/step - loss: 0.3435 - acc: 0.8966
Epoch 172/500
290/290 [==============================] - 3s 10ms/step - loss: 0.3709 - acc: 0.8931
Epoch 173/500
290/290 [==============================] - 3s 10ms/step - loss: 0.3669 - acc: 0.8862
Epoch 174/500
290/290 [==============================] - 3s 10ms/step - loss: 0.3563 - acc: 0.9103
Epoch 175/500
290/290 [=

290/290 [==============================] - 3s 10ms/step - loss: 0.1180 - acc: 0.9586
Epoch 248/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1163 - acc: 0.9586
Epoch 249/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1758 - acc: 0.9483
Epoch 250/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1703 - acc: 0.9483
Epoch 251/500
290/290 [==============================] - 3s 11ms/step - loss: 0.1845 - acc: 0.9448
Epoch 252/500
290/290 [==============================] - 3s 11ms/step - loss: 0.1586 - acc: 0.9586
Epoch 253/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1187 - acc: 0.9586
Epoch 254/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1707 - acc: 0.9517
Epoch 255/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1081 - acc: 0.9655
Epoch 256/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1157 - acc: 0.9621
Epoch 257/500
290/290 [=

290/290 [==============================] - 4s 13ms/step - loss: 0.1749 - acc: 0.9655
Epoch 330/500
290/290 [==============================] - 4s 14ms/step - loss: 0.0848 - acc: 0.9793
Epoch 331/500
290/290 [==============================] - 4s 14ms/step - loss: 0.0581 - acc: 0.9931
Epoch 332/500
290/290 [==============================] - 4s 14ms/step - loss: 0.1288 - acc: 0.9621
Epoch 333/500
290/290 [==============================] - 4s 13ms/step - loss: 0.0537 - acc: 0.9828
Epoch 334/500
290/290 [==============================] - 4s 14ms/step - loss: 0.0983 - acc: 0.9759
Epoch 335/500
290/290 [==============================] - 4s 15ms/step - loss: 0.1046 - acc: 0.9724
Epoch 336/500
290/290 [==============================] - 4s 13ms/step - loss: 0.1101 - acc: 0.9690
Epoch 337/500
290/290 [==============================] - 4s 14ms/step - loss: 0.0633 - acc: 0.9793
Epoch 338/500
290/290 [==============================] - 4s 15ms/step - loss: 0.0612 - acc: 0.9690
Epoch 339/500
290/290 [=

290/290 [==============================] - 3s 10ms/step - loss: 0.1296 - acc: 0.9793
Epoch 412/500
290/290 [==============================] - 3s 12ms/step - loss: 0.2012 - acc: 0.9621
Epoch 413/500
290/290 [==============================] - 3s 10ms/step - loss: 0.0575 - acc: 0.9897
Epoch 414/500
290/290 [==============================] - 3s 10ms/step - loss: 0.0535 - acc: 0.9931
Epoch 415/500
290/290 [==============================] - 3s 10ms/step - loss: 0.0874 - acc: 0.9759
Epoch 416/500
290/290 [==============================] - 3s 10ms/step - loss: 0.0633 - acc: 0.9828
Epoch 417/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1320 - acc: 0.9759
Epoch 418/500
290/290 [==============================] - 3s 10ms/step - loss: 0.0278 - acc: 0.9897
Epoch 419/500
290/290 [==============================] - 3s 10ms/step - loss: 0.0237 - acc: 0.9931
Epoch 420/500
290/290 [==============================] - 3s 10ms/step - loss: 0.1709 - acc: 0.9690
Epoch 421/500
290/290 [=

290/290 [==============================] - 4s 14ms/step - loss: 0.0347 - acc: 0.9931
Epoch 494/500
290/290 [==============================] - 3s 12ms/step - loss: 0.0255 - acc: 0.9931
Epoch 495/500
290/290 [==============================] - 3s 11ms/step - loss: 0.0222 - acc: 0.9966
Epoch 496/500
290/290 [==============================] - 4s 12ms/step - loss: 0.0081 - acc: 0.9966
Epoch 497/500
290/290 [==============================] - 3s 12ms/step - loss: 0.0286 - acc: 0.9931
Epoch 498/500
290/290 [==============================] - 3s 11ms/step - loss: 0.0279 - acc: 0.9931
Epoch 499/500
290/290 [==============================] - 3s 12ms/step - loss: 0.0035 - acc: 1.0000
Epoch 500/500
290/290 [==============================] - 3s 11ms/step - loss: 0.0191 - acc: 0.9931


In [13]:
input_test=[[[0, 0.5], [5, 0.5], [9, 0.5], [5, 0.5], [0, 0.5], [2, 0.5], [9, 0.5], 
             [5, 0.5], [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], [2, 0.5],
             [9, 0.5], [2, 0.5], [6, 0.5], [5, 0.5], [9, 0.5], [5, 0.5], [2, 0.5]]]
input_test=np.array(input_test)
print(model.predict(input_test))
print(model_2.predict(input_test))

[[3.5111009e-06 2.4148131e-10 7.6981008e-09 2.6793040e-10 3.3748078e-03
  2.7113006e-10 2.0343428e-05 2.7000502e-10 1.1053613e-05 1.8467931e-06
  9.9306315e-01 2.6423980e-10 1.6843836e-03 2.6054436e-10 7.6792028e-04
  2.1213968e-10 9.1708702e-05 8.6599061e-07 4.5806714e-04 1.3128893e-05
  2.4817320e-05 2.6478267e-10 4.4988009e-09 4.8034330e-04 3.7277794e-06
  2.4388455e-10 3.3624389e-07]]
[[1.1471830e-08 9.9999011e-01 7.1540777e-13 9.1404872e-06 1.1548602e-12
  3.8666251e-08 6.4259752e-13 8.0419509e-13 6.3983839e-13 7.6573895e-07]]


In [24]:
y=[[[0, 0.5], [5, 1], [9, 0.5], [5, 0.5], [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], 
            [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], [2, 0.5], [9, 0.5], [2, 0.5], [6, 0.5], 
            [5, 0.5], [9, 2], [5, 2], [3, 2]]]

x=np.array(y)
# temp1=model.predict(x)[0][0]
# temp2=model_2.predict(x)[0][0]
# print([temp1,temp2])
# print(x)
# y[0].append([temp1,temp2])
# del(y[0][0])
# z = np.array(y)
# temp3=model.predict(z)[0][0]
# temp4=model_2.predict(z)[0][0]
# print([temp3,temp4])
new_song=[[0, 0.5], [5, 1], [9, 0.5], [5, 0.5], [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], 
            [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], [2, 0.5], [9, 0.5], [2, 0.5], [6, 0.5], 
            [5, 0.5], [9, 2], [5, 2], [3, 2]]
print(new_song)
def conpose(y):
    x=np.array(y)
    temp1=np.argmax(model.predict(x)[0])/2
    temp2=(np.argmax(model_2.predict(x)[0])+1)/4
    #print([temp1,temp2])
    return [temp1,temp2]

for i in range(50):
    new_note = conpose(x)
    y[0].append(new_note)
    new_song.append(new_note)
    del(y[0][0])
    x = np.array(y)
print(new_song)
with open("./test/json/sunny_new_song.json","w") as f:
        json.dump(new_song,f)

[[0, 0.5], [5, 1], [9, 0.5], [5, 0.5], [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], [2, 0.5], [9, 0.5], [2, 0.5], [6, 0.5], [5, 0.5], [9, 2], [5, 2], [3, 2]]
[[0, 0.5], [5, 1], [9, 0.5], [5, 0.5], [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], [0, 0.5], [2, 0.5], [9, 0.5], [5, 0.5], [2, 0.5], [9, 0.5], [2, 0.5], [6, 0.5], [5, 0.5], [9, 2], [5, 2], [3, 2], [5.0, 0.5], [8.0, 0.5], [2.0, 0.5], [6.0, 0.5], [9.0, 0.5], [7.0, 0.5], [2.0, 0.5], [9.0, 0.5], [5.0, 0.5], [5.0, 0.5], [12.0, 0.5], [5.0, 0.5], [5.0, 0.5], [9.0, 0.5], [9.0, 0.5], [8.0, 0.5], [6.0, 1.0], [7.0, 0.5], [7.0, 0.5], [7.0, 0.5], [0.0, 0.5], [12.0, 0.5], [5.0, 0.5], [9.0, 0.5], [9.0, 1.0], [5.0, 1.0], [5.0, 1.0], [2.0, 1.0], [9.0, 0.25], [7.0, 0.5], [7.0, 1.0], [6.0, 0.5], [6.0, 0.25], [7.0, 0.5], [7.0, 0.5], [6.0, 0.5], [7.0, 0.5], [0.0, 0.5], [10.0, 0.5], [2.0, 0.5], [2.0, 0.5], [5.0, 1.0], [7.0, 0.5], [11.5, 0.25], [5.0, 0.5], [7.0, 0.5], [6.0, 0.5], [5.0, 1.0], [6.0, 0.5], [6.0, 0.5]]
